### ISSUE TITLE
Prevent load-snapshot.sh from triggering after completion

### ISSUE THREAD

**Issue by breezytm** [CryptoManufaktur-io/era-docker#2]
Hi, thank you for this. It's so hard to find any meaningful documentation on how to deployed a zkSync era node. I have read through the `load-snapshot.sh` script and I believe there is a flaw and I was wondering if you can help clarify it. I don't see any validation that is done in the script to verify, at startup, if the postgres dump task has already been completed. Meaning if after the node is fully synced and I restart it, the snapshot will download again and the postures dump restore as well. Can you please confirm this? I have updated the script locally to account for this but I simply wanted to make sure I did not miss it.

**Comment by yorickdowne** [comment]
This is not necessary. PostgreSQL will only run the snapshot script if the DB is not initialized. After initial load, PostgreSQL won't execute the snapshot script, and so the script itself need not check whether the DB already exists.
